### ISSUE TITLE
テストケース get_proxy_status が失敗する

### ISSUE THREAD

**Issue by naokikimura** [naokikimura/jubatus-node-client#3]
テストケース `get_proxy_status`を実行すると失敗する
```
$ npm test -- -t get_proxy_status

> jubatus@0.5.1 test ~/Documents/workspace/jubatus-node-client
> nodeunit test/ "-t" "get_proxy_status"


common
✖ get_proxy_status

Assertion Message: Error: 1 get_proxy_status
AssertionError:
Error: 1 get_proxy_status
    at Client.client.call (~/Documents/workspace/jubatus-node-client/index.js:67:46)
    at receive (~/Documents/workspace/jubatus-node-client/lib/msgpack-rpc.js:38:22)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Socket.<anonymous> (~/Documents/workspace/jubatus-node-client/node_modules/msgpack/lib/msgpack.js:77:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
==
null
    at Object.equal (~/Documents/workspace/jubatus-node-client/node_modules/nodeunit/lib/types.js:83:39)
    at constructor.<anonymous> (~/Documents/workspace/jubatus-node-client/test/common.js:105:18)
    at Client.client.call (~/Documents/workspace/jubatus-node-client/index.js:67:26)
    at receive (~/Documents/workspace/jubatus-node-client/lib/msgpack-rpc.js:38:22)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Socket.<anonymous> (~/Documents/workspace/jubatus-node-client/node_modules/msgpack/lib/msgpack.js:77:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

AssertionError: null == true
    at Object.ok (~/Documents/workspace/jubatus-node-client/node_modules/nodeunit/lib/types.js:83:39)
    at constructor.<anonymous> (~/Documents/workspace/jubatus-node-client/test/common.js:106:18)
    at Client.client.call (~/Documents/workspace/jubatus-node-client/index.js:67:26)
    at receive (~/Documents/workspace/jubatus-node-client/lib/msgpack-rpc.js:38:22)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Socket.<anonymous> (~/Documents/workspace/jubatus-node-client/node_modules/msgpack/lib/msgpack.js:77:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)


FAILURES: 2/2 assertions failed (151ms)
npm ERR! Test failed.  See above for more details.
```

**Comment by naokikimura** [comment]
jubatus サーバーに対して`get_proxy_status `を実行すると、エラーが返るようになっていたい。

参考: http://jubat.us/ja/api/common_structs.html#get_proxy_status
